### ISSUE TITLE
Doesn't pass AMP validation

### ISSUE THREAD

**Issue by dangayle** [tachyons-css/tachyons-amp#1]
There are a few issues with this version of Tachyons:

- The AMP spec disallows `!important` declarations.
- `.cf` cannot have the `.cf { *zoom: 1;}` clearfix hack, it doesn't pass the validator. Is it even necessary since we're not targeting IE?
- Is there a need for `-l` sizes, as AMP is intended for mobile use only?

**Comment by misscs** [comment]
@dangayle 
> Is there a need for -l sizes, as AMP is intended for mobile use only?

Really depends. If you have a separate mobile and desktop code base, then probably not. We serve a responsive site so we end up using relying on media queries.

**Comment by dangayle** [comment]
This is for AMP though, which never goes to desktop. Regular Tachyons is perfect for that.

--
Dan Gayle

**Comment by misscs** [comment]
Right. A responsive website serves both mobile and desktop. We don’t split out our code on our project. Desktop gets the benefit of performance because we’re designing/coding for AMP. If you have two different builds, then by all means slim the CSS code to your liking. 


> Em 27 de dez de 2017, à(s) 14:40, Dan Gayle <notifications@github.com> escreveu:
> 
> This is for AMP though, which never goes to desktop. Regular Tachyons is perfect for that.
> 
> --
> Dan Gayle
>

**Comment by dangayle** [comment]
You serve AMP pages to desktop and don’t use the regular Tachyons at all? It doesn’t validate as-is.

**Comment by misscs** [comment]
I use a modified build of standard Tachyons.

**Comment by mic-mart** [comment]
Hey! 👋 Is anyone working on making this pass AMP validation? Is there something I can help with? I love Tachyons, and I am trying to make it work for a big AMP project.

**Comment by johno** [comment]
No one's currently working on it to my knowledge, will gladly accept a PR if you'd like to lend a hand.

**Comment by mic-mart** [comment]
At first glance, `!important` is only used in the `debug`, `background-size` and `visibility` modules. Would it be acceptable to comment out these modules and just not support those for the AMP version?

**Comment by dangayle** [comment]
Cool. Thank you for fixing this.
